//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLVM.ClangTidy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LLVM.ClangTidy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonTidy {
            get {
                object obj = ResourceManager.GetObject("ButtonTidy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///Checks:
        ///   # This file should be updated when new checks are added, and eventually we should
        ///   # generate this file automatically from the .rst files in clang-tidy.
        ///  - Category:    CERT Secure Coding Standards
        ///    Label:       Overloaded allocation function pairs
        ///    Description: Checks for violations of CERT DCL54-CPP - Overload allocation and deallocation functions as a pair in the same scope
        ///    Name:        cert-dcl54-cpp
        ///  - Category:    C++ Core Guidelines
        ///    Label:       I.22 - Comple [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClangTidyChecks {
            get {
                return ResourceManager.GetString("ClangTidyChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Package {
            get {
                object obj = ResourceManager.GetObject("Package", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///Filters:
        ///  #Format output allowing auto navigation to source code line and column
        ///  - Pattern:     &quot;:(\d+):(\d+)&quot;
        ///    Replacement: &quot;($1,$2)&quot;
        ///  - Pattern:     &quot;.*(TPreprocessorGenerated).*(file not found).*\n.*\n.*\n&quot;
        ///    Replacement:
        ///  - Pattern:     &quot;.*file not found.*\n#include( *)&lt;.*&gt;.*\n.*&quot;
        ///    Replacement:
        ///  - Pattern:     &quot;\nwarning: .*\n&quot;
        ///    Replacement: &quot;\n&quot;
        ///.
        /// </summary>
        internal static string VSOutputFilter {
            get {
                return ResourceManager.GetString("VSOutputFilter", resourceCulture);
            }
        }
    }
}
